#!/usr/bin/env bash
# This script tells the story of the /etc/passwd file, describing each user's details.

# Read the /etc/passwd file line by line
while IFS=':' read -r username _ uid gid info homedir shell; do
    # Extract additional information
    group_name=$(getent group "$gid" | cut -d: -f1)
    passcode=$(echo "$info" | cut -c 2-)

    # Display the story for each user
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $info"
done < /etc/passwd
