#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop

# Counter variable
count=0

# Loop using until to display "Best School" 10 times
until [ $count -eq 10 ]; do
    echo "Best School"
    ((count++))
done
